### ISSUE TITLE
支援內嵌翻譯

### ISSUE THREAD

**Issue by SiongSng** [SiongSng/RPMTW-Update-Mod#8]
裝好此模組後，可以直接在Minecraft內使用Gui翻譯模組，目前因為技術問題仍然無解。

**Comment by baka-gourd** [comment]
或許隔壁的這個可能是個專案，就是也沒做www

**Comment by SiongSng** [comment]
wwww

**Comment by SiongSng** [comment]
目前認為可行的示意圖:
![圖片](https://user-images.githubusercontent.com/48402225/115948213-6602b000-a4ff-11eb-9c98-8f2c3b7fc333.png)

**Comment by SiongSng** [comment]
## 進度更新 - Forge  
### 目前可以使用GUI來翻譯惹www，功能也寫好了，正在優化錯誤以及支援Fabric。  
  
![圖片](https://user-images.githubusercontent.com/48402225/116770079-87b9e500-aa73-11eb-9d3a-5976f9174a1a.png)

**Comment by SiongSng** [comment]
第一個理想功能似乎成功惹，在1.0.9正式加入。
